---
name: Check Spelling

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Spelling
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
